apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: default
spec:
  selector:
    app: myapp # Matches the labels in your deployment
  ports:
    - protocol: TCP
      port: 80 # Port exposed by the service
      targetPort: 80 # Port exposed by the container
  type: ClusterIP # Use NodePort or LoadBalancer for external access
